-- VERIFICANDO AS TABLESPACE CRIADAS
SELECT *
FROM V$TABLESPACE;

-- CRIANDO TABLESPACE
CREATE TABLESPACE TBS_DADOSCURSO DATAFILE 'C:\app\Administrador\product\21c\oradata\tbs_dadoscurso.dbf' SIZE 100M;

-- DAR PERMISSÃO PARA CRIAR USUÁRIO
ALTER SESSION
SET "_ORACLE_SCRIPT"=TRUE;

-- CRIAR USUÁRIO
CREATE USER CURSO --Usuario
IDENTIFIED BY "123" --Senha
DEFAULT TABLESPACE TBS_DADOSCURSO
TEMPORARY TABLESPACE TEMP;

-- RETIRAR PERMISSÃO PARA CRIAR USUÁRIO
ALTER SESSION
SET "_ORACLE_SCRIPT"=FALSE;

-- VERIFICAR TABLESPACE EXISTENTES
SELECT *
FROM V$TABLESPACE;

-- DANDO TODAS AS PERMISSÕES DE DBA PARA O USUÁRIO "CURSO"
-- OBSERVAÇÃO, NÃO SE FAZ ISSO EM PRODUÇÃO
GRANT DBA TO CURSO;


-- PARA PODE UTILIZAR O ESPAÇO TODO, OU SEJA, SEM LIMITE
GRANT
UNLIMITED TABLESPACE TO CURSO;


-- EXCLUIR REGRA DE EXPIRAR SENHA DO ORACLE
ALTER PROFILE DEFAULT
LIMIT PASSWORD_LIFE_TIME
UNLIMITED;



-- EXCLUIR TABLESPACE
DROP TABLESPACE tbs_dadoscurso;