-- CRIANDO TABELA
-- O QUE É UM TABELA?
/*
IMAGINA UMA PLANILHA DE EXCEL, EM QUE ELA CONTÉM LINHAS E COLUNAS.
CADA LINHA É UM REGISTRO E CADA COLUNA É UMA INFORMAÇÃO.
*/

CREATE TABLE CLIENTE
(
   CODIGO NUMBER GENERATED ALWAYS AS IDENTITY, -- O COMANDO "GENERATED ALWAYS AS IDENTITY" FAZ COM QUE O CÓDIGO SEJA INSERIDO AUTOMATICAMENTE, OU SEJA, AUTO_INCREMENT DO ORACLE. EM VERSÕES ANTERIORES A 11G NÃO POSSUI O AUTOINCREMENTO DIRETO. 
   NOME VARCHAR(40)
);

-- INSERINDO DADOS NA TABELA
INSERT INTO CLIENTE (NOME) VALUES ('ADRIANO');

-- CONSULTANDO DADOS NA TABELA
SELECT * 
FROM CLIENTE;